from __future__ import annotations

import re
from enum import Enum
from urllib.parse import quote

from codedebrief.model import Flow, FlowNode, NodeKind, ProjectModel


def render_markdown(model: ProjectModel) -> str:
    entrypoints = [flow for flow in model.flows if flow.is_entrypoint]
    lines = [
        "# CodeDebrief Decision Flows",
        "",
        "> Generated from source code. Do not edit this file manually.",
        "",
        f"- **Generated:** {_code_span(model.generated_at)}",
        f"- **Source root:** {_code_span(model.root)}",
        f"- **Flows:** {len(model.flows)}",
        f"- **Entry points:** {len(entrypoints)}",
    ]
    scopes = model.metadata.get("scopes", {})
    if scopes:
        lines.append(
            "- **Scopes:** "
            + " · ".join(f"{_md_inline(name)} ({count})" for name, count in scopes.items())
        )
    lines.extend(["", "## Project Map", ""])
    lines.extend(_project_map(model, entrypoints))

    lines.extend(["", "## Entry Point Flows", ""])
    for flow in entrypoints:
        lines.extend(_flow_section(flow))

    subflows = [
        flow for flow in model.flows if not flow.is_entrypoint and not flow.metadata.get("test")
    ]
    if subflows:
        lines.extend(["", "## Referenced Subflows", ""])
        for flow in subflows:
            if flow.called_by:
                lines.extend(_flow_section(flow))

    return "\n".join(lines).rstrip() + "\n"


def _project_map(model: ProjectModel, entrypoints: list[Flow]) -> list[str]:
    if not entrypoints:
        return ["No entry points were detected."]
    by_id = {flow.id: flow for flow in model.flows}
    lines = ["```mermaid", "flowchart TD"]
    rendered_nodes: set[str] = set()
    for flow in entrypoints:
        lines.append(f'  {_mermaid_id(flow.id)}["{_escape(flow.name)}"]')
        rendered_nodes.add(flow.id)
    rendered: set[tuple[str, str]] = set()
    for flow in entrypoints:
        for target_id in flow.calls:
            target = by_id.get(target_id)
            if target is None:
                continue
            pair = (flow.id, target.id)
            if pair in rendered:
                continue
            rendered.add(pair)
            if target.id not in rendered_nodes:
                lines.append(f'  {_mermaid_id(target.id)}["{_escape(target.name)}"]')
                rendered_nodes.add(target.id)
            lines.append(f"  {_mermaid_id(flow.id)} --> {_mermaid_id(target.id)}")
    lines.append("```")
    return lines


def _flow_section(flow: Flow) -> list[str]:
    source = _source_reference(flow.location.path, flow.location.start_line)
    lines = [
        f"### {_md_inline(flow.name)}",
        "",
        f"{_code_span(flow.entry_kind)} · {_code_span(flow.language)} · "
        f"{_code_span(flow.framework)} · {source}",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for node in flow.nodes:
        lines.append(f"  {_render_node(node)}")
    for edge in flow.edges:
        label = f'|"{_escape(edge.label)}"|' if edge.label else ""
        lines.append(f"  {_mermaid_id(edge.source)} -->{label} {_mermaid_id(edge.target)}")
    lines.append("```")
    lines.append("")
    return lines


def _enum_value(value: object) -> str:
    if isinstance(value, Enum):
        return str(value.value)
    return str(value)


def _render_node(node: FlowNode) -> str:
    node_id = _mermaid_id(node.id)
    label = _escape(node.label)
    if node.kind is NodeKind.DECISION:
        return f'{node_id}{{"{label}"}}'
    if node.kind is NodeKind.CALL:
        return f'{node_id}[["{label}"]]'
    if node.kind is NodeKind.ERROR:
        return f'{node_id}{{{{"{label}"}}}}'
    if node.kind in {NodeKind.ENTRY, NodeKind.TERMINAL}:
        return f'{node_id}(["{label}"])'
    return f'{node_id}["{label}"]'


def _mermaid_id(value: str) -> str:
    return "m" + "".join(character if character.isalnum() else "_" for character in value)


def _escape(value: str) -> str:
    # Mermaid quoted labels: neutralize quote breakout and HTML so a source-derived
    # label can't malform the diagram or smuggle markup.
    return (
        value.replace("\\", "\\\\")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", " ")
    )


# Inline metacharacters that could turn source-derived text into a live link, emphasis,
# code span, table cell, or raw HTML in a committed report.
_MD_INLINE_SPECIAL = re.compile(r"([\\`*_\[\]()<>|#~])")


def _md_inline(value: str) -> str:
    """Escape a source-derived string for safe inline Markdown prose."""
    collapsed = re.sub(r"\s+", " ", value)
    return _MD_INLINE_SPECIAL.sub(r"\\\1", collapsed)


def _code_span(value: str) -> str:
    """Render a label as an inline code span, neutralizing backtick breakout."""
    return "`" + value.replace("`", "'").replace("\n", " ") + "`"


def _source_reference(path: str, line: int) -> str:
    # The path is source-derived (a file name an attacker could choose). Neutralize
    # backtick breakout in the visible inline-code span, and percent-encode the link
    # destination so a `)`, `<`, `>`, or space can't close the link or smuggle markup.
    label = _code_span(f"{path}:{line}")
    destination = quote(f"../{path}", safe="/")
    return f"[{label}]({destination}#L{line})"
